theme: jekyll-theme-architect

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/ricemichelle/
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mlrice"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:mrice915@hotmail.com
